### ISSUE TITLE
[Documentation] Update the oas to v3

### ISSUE THREAD

**Issue by silversoul93** [mia-platform/crud-service#100]
## Feature Description
As reported in [this discussion](https://github.com/mia-platform/community/discussions/266), the `crud-service` could be enabled to return the v3 openapi documentation instead of the v2.

This feature could be parametrized through a `OPENAPI_SPECIFICATION_VERSION` environment variable.

**Comment by danibix95** [comment]
Hi! Thanks for the feedback.

I believe this option can be enabled changing this parameter here: https://github.com/mia-platform/crud-service/blob/main/index.js#L263

We'll experiment with it and let you know the outcome.

**Comment by danibix95** [comment]
Hi @silversoul93, this issue has been solved by #285 and included in version `v7.0.1` of CRUD Service
