### ISSUE TITLE
operators $addToSet and $pull are not correctly supported when json schema is not defined

### ISSUE THREAD

**Issue by SimoneBergonzi** [mia-platform/crud-service#106]
**Description**
When performing a PATCH /bulk using operator `$addToSet` (or `$pull`) on a property of type `object` with no JSON schema defined, the service replies with:

```
code: 400
error: body must NOT have additional properties. Property \"metadata.company_data.prop\" is not defined in validation schema
```

**Environment**
image: ghcr.io/mia-platform/crud-service:6.6.1

**Minimal Reproduction**
property "metadata" -> type: object
JSON schema left empty

Request payload KO:
```
[
  {
      "filter": {
          "_id": "646dc217f5d2cff214c8d55e"
      },
      "update": {
          "$addToSet": {
              "metadata.company_data.prop": "111"
          }
      }
  }
]
```

**Additional context**
There are no problems when performing the same operation defining the JSON schema of `metadata` as follows:
```
{
  additionalProperties: true
}
```

**Comment by danibix95** [comment]
Hi @SimoneBergonzi, I believe this is not a problem, considered it is expected that CRUD Service validates against the schema which operations can be carried out on the underlying collection.

Therefore, by default any operation on properties not defined in the schema are forbidden. However, as you highlighted, by defining the specific schema or allowing a relaxed schema (with `additionalProperties: true`) then such operations become available to employed.

Is this behavior reported in the documentation? On the contrary, would be sufficient to document it to solve this issue?
