### ISSUE TITLE
Add deletedAt date to default metadata

### ISSUE THREAD

**Issue by silversoul93** [mia-platform/crud-service#161]
## Feature Description

I'd like to have a new default metadata, the `deletedAt` date, to be added when the `__STATE__` of a document is set to `DELETED`.
We use the `__STATE__=DELETED` for virtual delete but often, after a while, the virtual delete should be definitive. With a `deletedAt` metadata we can use TTL indexes to automatically delete documents after an expiration period of time (e.g. 30 days).

## Desired solution

`deletedAt` metadata of type `Date`.

**Comment by danibix95** [comment]
Isn't the `updatedAt` field sufficient to achieve this behavior? You can add a TTL index on it so that documents are effectively deleted in the desired manner.

Theoretically, once the document enters `DELETED` state, your application won't update it anymore.

**Comment by EdoCrippaOfficial** [comment]
As @danibix95 said, you can also make a TTL _partial_ index over the `updatedAt` only bound to the `DELETED` entries to to get what you requested.

**Comment by silversoul93** [comment]
Thanks for your replies guys.

@danibix95 the `updatedAt` with a TTL index is not usable, if a document isn't updated for a while the TTL index could cause its deletion.

@EdoCrippaOfficial I didn't remember about partial indexes, with the TTL Partial index I think the `deletedAt` field is unnecessary.
