### ISSUE TITLE
Accept Header Validation Is Too Restrictive

### ISSUE THREAD

**Issue by GioAc96** [mia-platform/crud-service#172]
**Description**
The validation of the `Accept` request header for the `/export` endpoint has become too restrictive in version `6.9.0` (due to [this pr](https://github.com/mia-platform/crud-service/pull/137)). Requests with the header set to values indicating that multiple formats are accepted (ike `application/json, application/ndjson`) now cause a `400: Bad Request` response:
```JSON
{
  "statusCode": 400,
  "code": "FST_ERR_VALIDATION",
  "error": "Bad Request",
  "message": "headers/accept must be equal to one of the allowed values"
}
```

**Environment**

I'm using CRUD Service version 6.9.0

**Minimal Reproduction**
```CURL
curl \
--location 'http://crud-service/collection/export' \
--header 'Accept: application/json, */*'
```

**Comment by amountainram** [comment]
@danibix95 we could it fix by removing:

`"enum"`

and adding

`"patterm": "(\*\/\*|application\/ndjson)"`?

**Comment by danibix95** [comment]
New service version `v6.9.1` has been released, which fixes this issue
