### ISSUE TITLE
Add API to hide indexes of a collection

### ISSUE THREAD

**Issue by flower-of-the-bridges** [mia-platform/crud-service#185]
## Feature Description
Some indexes of a collection may be useful only a startup, and then not used again. It would be nice to add an API to enable the usage of hidden indexes

## Desired solution
It would be nice to add a route such as 

```
POST /<collection-name>/indexes/<index-name>/hide
```

which returns an object such as

```
{
  hidden: <true|false>
}
```

This API should implement the MongoDB driver apis described [in this doc page](https://www.mongodb.com/docs/manual/core/index-hidden/#examples).

Also, at startup, I can decide which index is hidden by default

**Comment by danibix95** [comment]
Hi @flower-of-the-bridges, thanks for proposing a new feature for CRUD Service.

However, we believe this feature for indexes hiding might get quite dangerous whenever a user disables indexes and then forgets to re-enable them (especially in production environments).  
In addition, whoever has access to the collection via CRUD Service may call such API in case it isn't properly protected, which could cause further access issues.

For this reasons, we would close the issue.
