### ISSUE TITLE
GET /-/schemas with Accept: */* returns 400

### ISSUE THREAD

**Issue by GioAc96** [mia-platform/crud-service#286]
**Description**

When calling the `GET /-/schemas` endpoint, if the `Accept` request header is set to `*/*` (the default value in Postman), the endpoint returns a `400: Bad Request` with the following response body:
```json
{
    "statusCode": 400,
    "code": "FST_ERR_VALIDATION",
    "error": "Bad Request",
    "message": "headers/accept must be equal to one of the allowed values"
}
```

This also happens if the client does not set the `Accept` request header, which I believe to also be an undesired behavior.

**Environment**

I'm using the `latest` version of the CRUD service from Docker Hub

**Minimal Reproduction**

```curl
curl --header 'Accept: */*' --location 'http://crud-service:3000/-/schemas'
```

**Comment by flower-of-the-bridges** [comment]
Hi @GioAc96 

I can say (also here) that is indeed a bug! It will be fixed with PR [#331](https://github.com/mia-platform/crud-service/pull/331)
