### ISSUE TITLE
upsert-one - support $addToSet array update operator

### ISSUE THREAD

**Issue by TheRusCompass** [mia-platform/crud-service#3]
## Issue

* Mongo update operators for arrays are specified [here](https://docs.mongodb.com/manual/reference/operator/update/#array)
* Among the ones specified above, the CRUD service at the moment supports only the `$push`
* Using `$addToSet` in the body of an upsert-one HTTP POST request thus results in a 400 bad request response

**Comment by danibix95** [comment]
This feature has been merged into main an it will be soon available in the next service release
