### ISSUE TITLE
Export CSV Does Not Include Column Of Optional Field

### ISSUE THREAD

**Issue by GioAc96** [mia-platform/crud-service#303]
**Description**
When calling the `/export` endpoint with the `Accept` header set to `text/csv`, the CRUD Service returns a CSV that does not always include all columns specified in the `_p` (or `_rawp`) parameters.

In fact, when I do the following CURL:
```curl
curl --location 'http://crud-service/stops/export?_p=navigator_code%2Ctrenitalia_stop_id%2Cuic_code%2Citalo_stop_id%2Cstop_name%2Cstop_lat%2Cstop_lon' \
--header 'Accept: text/csv'
```
It correctly returns me a JSON lines document, where each line contains the specified fields where present, like so:

```json
{
    "_id": "662fa93b13aece4560b8e996",
    "stop_name": "Olevano",
    "navigator_code": "OLV",
    "uic_code": "8300036",
    "stop_lat": 45.21211935,
    "stop_lon": 8.711819187,
    "trenitalia_stop_id": "830000036"
}
{
    "_id": "662fa93b13aece4560b8e995",
    "stop_name": "Torino Porta Susa",
    "navigator_code": "OUE",
    "uic_code": "8300035",
    "stop_lat": 45.07410038,
    "stop_lon": 7.667250023,
    "italo_stop_id": "OUE",
    "trenitalia_stop_id": "830000222"
}
```
Notice how only the second document has the `italo_stop_id` field, since it is not present in the first document. However, when exporting a CSV, the column `italo_stop_id` is omitted.

Here is the CSV export CURL that I'm using:
```curl
curl --location 'http://crud-service/stops/export?_p=navigator_code%2Ctrenitalia_stop_id%2Cuic_code%2Citalo_stop_id%2Cstop_name%2Cstop_lat%2Cstop_lon' \
--header 'Accept: text/csv'
```

And here is the output, which omits the `italo_stop_id` column:

```csv
_id,stop_name,navigator_code,uic_code,stop_lat,stop_lon,trenitalia_stop_id
662fa93b13aece4560b8e97d,Villadossola,VLD,8300001,46.06415148,8.264690648,830000001
662fa93b13aece4560b8e97e,Pallanzeno,PAZ,8300002,46.0435374,8.26067037,830000002
...
```

The behaviour is analogous when using the `_rawp` query parameter to specify the desired response fields.

**Environment**

I'm using CRUD Service version 6.9.4

**Additional context**

It might be that the `csv-stringify` module that I assume is being used to convert the content to `CSV` includes only the fields from the first document, therefore if the first document does not have an optional field it is then omitted from the export

**Comment by danibix95** [comment]
Hi @GioAc96! This issues has been resolved in #300 and it has been released within version `v7.0.2` of CRUD Service.

Please let us know whether after the upgrade the issue disappears.
