### ISSUE TITLE
The CRUD collection definition is a JSON Schema

### ISSUE THREAD

**Issue by TheRusCompass** [mia-platform/crud-service#4]
It might be useful to use as crud collection definition a JSON Schema instead of generating it later in code.
This would enable the implementation of a number of features more easily. It would be possible to:

* Perform fields validations against the schema (min, max, regex ecc...)
* Instantiate a crud-service by passing a JSON schema in a config map or set of config maps.

Moreover we talked about the possibility of using a json schema as "new cms" collections configuration. The crud collection schema could be the default one.

**Comment by danibix95** [comment]
This has been addressed by #65
