### ISSUE TITLE
$unionWith operator is not supported in MongoDB Views

### ISSUE THREAD

**Issue by danielemarostica** [mia-platform/crud-service#44]
**Description**
Hi, 

I'm trying to create a MongoDB View to retrieve documents from the **_union_** of two unrelated collections.
(ndr: basically a "Full Outer Join" operation in a SQL database.)

To do this in MongoDB there's the [`$unionWith` operator](https://www.mongodb.com/docs/manual/reference/operator/aggregation/unionWith/), but it seems not supported by the CRUD Service.

e.g
collection `dogs` 
```json
[
  { "name": "dog 1", "image": "🐕" },
  { "name": "dog 2", "image": "🐩" },
  { "name": "dog 3", "image": "🐶" },
]
```

collection `cats` 
```json
[
  { "name": "cat 1", "image": "🐈" },
  { "name": "cat 2", "image": "🐱" },
]
```

expected view `animals`:
```json
[
  { "name": "dog 1", "image": "🐕", "type": "dog" },
  { "name": "dog 2", "image": "🐩", "type": "dog" },
  { "name": "dog 3", "image": "🐶", "type": "dog" },
  { "name": "cat 1", "image": "🐈", "type": "cat" },
  { "name": "cat 2", "image": "🐱", "type": "cat" },
]
```

to do this i created a MongoDB View with the following aggregation pipeline:

```json
[
  {
    "$project": {
      "name": 1,
      "image": 1,
      "type": "dog"
    }
  },
  {
    "$unionWith": {
      "coll": "cats",
      "pipeline": [
        {
          "$set": {
            "type": "cat"
          }
        }
      ]
    }
  },
  {
    "$project": {
      "name": 1,
      "image": 1,
      "type": 1
    }
  }
]
```

Expected result: array of 5 animals
Actual result: an empty array

I managed to create this view in a local MongoDB instance by running
`db.createView("animals", "dogs", [ _the pipeline above_ ])`

and by running `db.animals.find()` i get the expected result:
```
local> db.animals.find()
[
  {
    _id: ObjectId("64077d45ffc27717cb76e3fb"),
    name: 'dog 1',
    image: '🐕',
    type: 'dog'
  },
  {
    _id: ObjectId("64077d45ffc27717cb76e3fc"),
    name: 'dog 2',
    image: '🐩',
    type: 'dog'
  },
  {
    _id: ObjectId("64077d45ffc27717cb76e3fd"),
    name: 'dog 3',
    image: '🐶',
    type: 'dog'
  },
  {
    _id: ObjectId("64077d69ffc27717cb76e3fe"),
    name: 'cat 1',
    image: '🐈',
    type: 'cat'
  },
  {
    _id: ObjectId("64077d69ffc27717cb76e3ff"),
    name: 'cat 2',
    image: '🐱',
    type: 'cat'
  }
]
```

**Environment**
I'm using CRUD Service version 6.3.0 from GitHub

**Comment by ianFar96** [comment]
Hi @danielemarostica

For the MongoDB View pipelines it is necessary that all $project and similar operators that filter the resulting fields have the `__STATE__` property to 1. This is because the CRUD service by default filters all documents by `__STATE__ = PUBLIC` when retrieving data.

This is not properly documented so we're gonna add it to the docs ASAP to avoid future confusions.

Thank you for making us notice!

**Comment by danibix95** [comment]
Documentation has been updated to clarify the need of `__STATE__` field in records produced by a view aggregation pipeline, so that CRUD Service operations also consider those records in result set.
