### ISSUE TITLE
If setting `openapi` to lc39 configuration, crud routes are not shown in api-portal

### ISSUE THREAD

**Issue by TheRusCompass** [mia-platform/crud-service#7]
After the upgrade to lc39 to v5, we forced `openApiSpecification: 'swagger'` inside the `swaggerDefinition`.
Using the default values, the apis are not listed in api-portal

**Comment by danibix95** [comment]
This has been fixed. Furthermore, due to #285 it is possible to choose the version of OpenAPI specification that it is preferred
