### ISSUE TITLE
dot notation with operator $set is not correctly supported on additional propertis at firt level

### ISSUE THREAD

**Issue by SimoneBergonzi** [mia-platform/crud-service#88]
**Description**
When performing a PATCH /bulk using `dot notation` on operator `$set` to set an additional property in an object defined with `additionalProperties: true` the service replies with:
```
code: 400
error: body must NOT have additional properties. Property \"metadata.additional_prop\" is not defined in validation schema
```

**Environment**
image: ghcr.io/mia-platform/crud-service:6.5.2

**Minimal Reproduction**
JSON schema (property "metadata"):
```
{
  "properties": {
    "company_data": {
      "type": "object",
      "properties": {
        "business_name": {
          "type": "string"
        }
      },
      "additionalProperties": true
    }
  },
  "additionalProperties": true,
  "type": "object"
}
```

Request payload KO:
```
[
  {
      "filter": {
          "_id": "646dc217f5d2cff214c8d55e"
      },
      "update": {
          "$set": {
              "metadata.additional_prop": "prop_val"
          }
      }
  }
]
```

**Additional context**
There are no problems with nested object defined with `additionalProperties: true`.
The schema is valid when performing a request with the following payload:
```
[
  {
      "filter": {
          "_id": "646dc217f5d2cff214c8d55e"
      },
      "update": {
          "$set": {
              "metadata.company_data.additional_prop": "prop_val"
          }
      }
  }
]
```

Also, there are no problems when not using the dot notation:
The schema is valid when performing a request with the following payload:
```
[
  {
      "filter": {
          "_id": "646dc217f5d2cff214c8d55e"
      },
      "update": {
          "$set": {
              "metadata":{
                  "additional_prop": "prop_val"
              }
          }
      }
  }
]
```

**Comment by giuliowaitforitdavide** [comment]
The fix for this bug will be available in the next release
