### ISSUE TITLE
operators $addToSet and $pull are not supported on additional properties

### ISSUE THREAD

**Issue by SimoneBergonzi** [mia-platform/crud-service#89]
**Description**
When performing a PATCH /bulk using operator `$addToSet` (or `$pull`) on a property not defined in the JSON schema, but under an object defined with `additionalProperties: true` the service replies with:

```
code: 400
error: body must NOT have additional properties. Property \"metadata.company_data.additionalArray\" is not defined in validation schema
```

**Environment**
image: ghcr.io/mia-platform/crud-service:6.5.2

**Minimal Reproduction**
JSON schema (property "metadata"):

```
{
  "properties": {
    "company_data": {
      "type": "object",
      "properties": {
        "employees": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "additionalProperties": true
    }
  },
  "additionalProperties": true,
  "type": "object"
}
```

Request payload KO:

```
[
  {
      "filter": {
          "_id": "646dc217f5d2cff214c8d55e"
      },
      "update": {
          "$addToSet": {
              "metadata.company_data.additionalArray": "111"
          }
      }
  }
]
```

**Additional context**
There are no problems when performing the same operation on array property defined in the schema.
The schema is valid when performing a request with the following payload:

```
[
  {
      "filter": {
          "_id": "646dc217f5d2cff214c8d55e"
      },
      "update": {
          "$addToSet": {
              "metadata.company_data.employees": "111"
          }
      }
  }
]
```

**Comment by giuliowaitforitdavide** [comment]
The fix for this bug will be available in the next release
